# Generated by Django 3.2.3 on 2021-06-10 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('nombre_servicio', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Nombre Servicio')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.CharField(max_length=250)),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo')),
                ('nombre_tipo', models.CharField(max_length=50, verbose_name='Tipo de vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('marca', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Marca')),
                ('annio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipovehiculo')),
            ],
        ),
    ]
