# Generated by Django 3.2.3 on 2021-06-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='idServicio',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Id Servicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre_servicio',
            field=models.CharField(max_length=25, verbose_name='Nombre Servicio'),
        ),
    ]
