# Generated by Django 3.2.3 on 2021-06-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210613_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='idServicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
